[project]
name = "my_dotfiles"
version = "0.0.1"
required-python = ">=3.12.3"
dependencies = [
    "pyright==1.1.408",
    "ruff==0.14.14",
    "pytest==9.0.2",
    "pytest-mock==3.15.1",
    "debugpy==1.8.19",
]

[tool.uv]
package = false
