[project]
name = "my_dotfiles"
version = "0.0.1"
required-python = ">=3.12.3"
dependencies = [
    "pyright==1.1.407",
    "ruff==0.14.3",
    "pytest==8.4.2",
    "pytest-mock==3.15.1",
    "debugpy==1.8.17",
]

[tool.uv]
package = false
