[project]
name = "my_dotfiles"
version = "0.0.1"
dependencies = [
  "debugpy==1.8.20",
  "pyright==1.1.408",
  "pytest==9.0.2",
  "pytest-mock==3.15.1",
  "ruff==0.14.14",
]
required-python = ">=3.12.3"

[tool.uv]
package = false
